#!/bin/bash
# vn.py Web界面使用演示脚本

echo "=========================================="
echo "  vn.py 量化交易平台 - 演示脚本"
echo "=========================================="
echo ""

echo "🌟 vn.py Web界面功能演示"
echo ""
echo "📱 这是一个功能完整的量化交易Web应用，包含："
echo ""
echo "1️⃣  策略回测功能"
echo "   - 支持4种经典策略"
echo "   - 可视化参数调整"
echo "   - 一键回测执行"
echo "   - 详细结果展示"
echo ""
echo "2️⃣ 智能选股功能"
echo "   - 5种选股策略"
echo "   - 全市场扫描（5000+股票）"
echo "   - 自定义筛选条件"
echo "   - 实时结果展示"
echo ""
echo "3️⃣ 策略对比功能"
echo "   - 多策略同时回测"
echo "   - 自动识别最佳策略"
echo "   - 风险收益分析"
echo "   - 可视化对比展示"
echo ""

echo "🚀 快速启动指南"
echo ""
echo "步骤1：安装依赖"
echo "-----------------------------------"
echo "cd /Users/w4sh8899/project/vnpy"
echo "source venv/bin/activate"
echo "pip install Flask Werkzeug"
echo ""

echo "步骤2：启动Web服务"
echo "-----------------------------------"
echo "./start_web.sh"
echo ""

echo "步骤3：访问界面"
echo "-----------------------------------"
echo "在浏览器中打开："
echo "http://localhost:5000"
echo ""

echo "📖 功能使用说明"
echo ""
echo "【策略回测】"
echo "1. 点击策略卡片选择要回测的策略"
echo "2. 调整策略参数（可选）"
echo "3. 设置回测时间范围"
echo "4. 点击'开始回测'按钮"
echo "5. 查看回测结果表格"
echo ""

echo "【智能选股】"
echo "1. 选择选股策略（超卖/超买/突破等）"
echo "2. 调整筛选条件（价格/成交量等）"
echo "3. 点击'开始选股'按钮"
echo "4. 查看选股结果列表"
echo ""

echo "【策略对比】"
echo "1. 选择2-4个策略进行对比"
echo "2. 设置对比时间范围"
echo "3. 点击'开始对比'按钮"
echo "4. 查看对比结果和最佳策略"
echo ""

echo "💡 使用建议"
echo ""
echo "1. 日常使用流程："
echo "   - 每天盘后：运行选股，寻找机会"
echo "   - 每周：对比策略表现，优化参数"
echo "   - 每月：回测验证策略有效性"
echo ""

echo "2. 风险控制："
echo "   - 不要盲目跟随选股结果"
echo "   - 结合基本面分析"
echo "   - 设置止损止盈"
echo "   - 控制仓位比例"
echo ""

echo "3. 参数优化："
echo "   - 布林带参数：周期10-20天，倍数1.5-2.0"
echo "   - 动量参数：周期10-20天，阈值0.3%-0.5%"
echo "   - 双均线参数：快线5-10天，慢线20-30天"
echo ""

echo "🎯 实战案例"
echo ""
echo "案例1：寻找超卖反弹机会"
echo "-----------------------------------"
echo "策略：超卖策略"
echo "参数：价格10-50元，成交量500万+"
echo "操作：选股 → 分析基本面 → 分批建仓 → 止损-5% → 止盈+10%"
echo ""

echo "案例2：策略参数优化"
echo "-----------------------------------"
echo "目标：优化布林带策略"
echo "方法：回测不同参数组合 → 选择夏普比率最高的参数"
echo "建议：ma_window=10, dev_mult=1.5"
echo ""

echo "📊 预期回测结果"
echo ""
echo "基于5只A股（2020-2025年）的历史表现："
echo ""
echo "策略           总收益率   夏普比率   最大回撤"
echo "-------         --------   --------   --------"
echo "布林带策略      +19.62%     0.29      -24.15%"
echo "Dual Thrust    +23.09%     0.20      -41.00%"
echo "双均线         -0.38%     -0.29      -0.73%"
echo "动量策略      -12.68%     -0.04      -31.99%"
echo ""

echo "⚠️  重要提示"
echo ""
echo "1. 历史表现不代表未来收益"
echo "2. 量化策略存在亏损风险"
echo "3. 建议从小资金开始测试"
echo "4. 严格执行风险控制"
echo "5. 持续学习和优化策略"
echo ""

echo "🔧 技术支持"
echo ""
echo "项目地址：https://github.com/w4sh/vnpy"
echo "使用文档：docs/web_app_guide.md"
echo "策略说明：docs/strategy_summary.md"
echo "选股指南：docs/stock_picker_guide.md"
echo ""

echo "=========================================="
echo "  现在可以启动Web界面了！"
echo "  运行：./start_web.sh"
echo "=========================================="